-- 大会情報の手動更新要求
-- 既存のSQLを実行済みの場合も、このファイルを最後まで再実行してください。

create table if not exists public.tournament_update_requests (
  id bigint generated by default as identity primary key,
  status text not null default 'pending' check (status in ('pending','processing')),
  requested_at timestamptz not null default now(),
  processing_started_at timestamptz
);

alter table public.tournament_update_requests enable row level security;

drop policy if exists "public can create tournament update request" on public.tournament_update_requests;
create policy "public can create tournament update request"
  on public.tournament_update_requests
  for insert
  to anon, authenticated
  with check (status = 'pending');

revoke all on public.tournament_update_requests from anon, authenticated;
grant insert on public.tournament_update_requests to anon, authenticated;

-- GitHub Actionsを直接起動する関数。
-- 事前にSupabase Vaultへ github_tournament_dispatch_token を登録してください。
create or replace function public.request_tournament_update()
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  github_token text;
  request_id bigint;
begin
  insert into public.tournament_update_requests(status)
  values ('pending')
  returning id into request_id;

  select decrypted_secret
    into github_token
    from vault.decrypted_secrets
   where name = 'github_tournament_dispatch_token'
   limit 1;

  if github_token is null then
    raise exception 'GitHub dispatch token is not configured in Supabase Vault';
  end if;

  perform net.http_post(
    url := 'https://api.github.com/repos/8tjf8htbch-maker/kokudai/dispatches',
    headers := jsonb_build_object(
      'Accept', 'application/vnd.github+json',
      'Authorization', 'Bearer ' || github_token,
      'X-GitHub-Api-Version', '2022-11-28',
      'Content-Type', 'application/json'
    ),
    body := jsonb_build_object(
      'event_type', 'tournament-update',
      'client_payload', jsonb_build_object(
        'request_id', request_id
      )
    )
  );

  return true;
end;
$$;

revoke all on function public.request_tournament_update() from public;
grant execute on function public.request_tournament_update() to anon, authenticated;

create or replace function public.claim_tournament_update_request()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.tournament_update_requests
     set status = 'processing',
         processing_started_at = now()
   where id = (
     select id
       from public.tournament_update_requests
      where status = 'pending'
      order by requested_at asc
      limit 1
      for update skip locked
   );

  return found;
end;
$$;

revoke all on function public.claim_tournament_update_request() from public;
grant execute on function public.claim_tournament_update_request() to anon, authenticated;
