-- 大会情報の手動更新要求
-- Supabase SQL Editorで1回実行してください。

create table if not exists public.tournament_update_requests (
  id bigint generated by default as identity primary key,
  status text not null default 'pending' check (status in ('pending','processing')),
  requested_at timestamptz not null default now(),
  processing_started_at timestamptz
);

alter table public.tournament_update_requests enable row level security;

drop policy if exists "public can create tournament update request" on public.tournament_update_requests;
create policy "public can create tournament update request"
  on public.tournament_update_requests
  for insert
  to anon, authenticated
  with check (status = 'pending');

revoke all on public.tournament_update_requests from anon, authenticated;
grant insert on public.tournament_update_requests to anon, authenticated;

create or replace function public.request_tournament_update()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tournament_update_requests(status)
  values ('pending');

  return true;
end;
$$;

revoke all on function public.request_tournament_update() from public;
grant execute on function public.request_tournament_update() to anon, authenticated;

create or replace function public.claim_tournament_update_request()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.tournament_update_requests
     set status = 'processing',
         processing_started_at = now()
   where id = (
     select id
       from public.tournament_update_requests
      where status = 'pending'
      order by requested_at asc
      limit 1
      for update skip locked
   );

  return found;
end;
$$;

revoke all on function public.claim_tournament_update_request() from public;
grant execute on function public.claim_tournament_update_request() to anon, authenticated;
