const POEMS=["秋の田の　かりほの庵の　苫をあらみ","春過ぎて　夏来にけらし　白妙の","あしびきの　山鳥の尾の　しだり尾の","田子の浦に　うち出でて見れば　白妙の","奥山に　もみぢふみわけ　鳴く鹿の","かささぎの　渡せる橋に　おく霜の","天の原　ふりさけ見れば　春日なる","わが庵は　都のたつみ　しかぞすむ","花の色は　うつりにけりな　いたづらに","これやこの　行くも帰るも　別れては","わたの原　八十島かけて　漕ぎ出でぬと","天つ風　雲のかよひ路　吹きとぢよ","つくばねの　峰よりおつる　みなの川","みちのくの　しのぶもぢずり　誰ゆゑに","君がため　春の野に出でて　若菜つむ","たち別れ　いなばの山の　峰に生ふる","ちはやぶる　神代もきかず　竜田川","すみの江の　岸に寄る波　よるさへや","難波潟　短き芦の　ふしの間も","わびぬれば　いまはたおなじ　難波なる","いま来むと　いひしばかりに　長月の","吹くからに　秋の草木の　しをるれば","月見れば　ちぢに物こそ　悲しけれ","このたびは　ぬさもとりあへず　手向山","なにしおはば　逢坂山の　さねかづら","小倉山　峰のもみぢ葉　心あらば","みかの原　わきて流るる　いづみ川","山里は　冬ぞさびしさ　まさりける","心あてに　折らばや折らむ　初霜の","有明の　つれなく見えし　別れより","朝ぼらけ　有明の月と　見るまでに","山川に　風のかけたる　しがらみは","ひさかたの　光のどけき　春の日に","誰をかも　知る人にせむ　高砂の","人はいさ　心もしらず　ふるさとは","夏の夜は　まだ宵ながら　明けぬるを","白露に　風の吹きしく　秋の野は","忘らるる　身をば思はず　ちかひてし","浅茅生の　小野の篠原　しのぶれど","しのぶれど　色に出でにけり　わが恋は","恋すてふ　わが名はまだき　立ちにけり","契りきな　かたみに袖を　しぼりつつ","あひみての　後の心に　くらぶれば","逢ふことの　たえてしなくば　なかなかに","あはれとも　いふべき人は　思ほえで","由良のとを　わたる舟人　かぢをたえ","八重葎　しげれる宿の　さびしきに","風をいたみ　岩うつ波の　おのれのみ","みかきもり　衛士のたく火の　夜はもえ","君がため　惜しからざりし　命さへ","かくとだに　えやはいぶきの　さしも草","明けぬれば　暮るるものとは　知りながら","嘆きつつ　ひとりぬる夜の　明くるまは","忘れじの　ゆくすゑまでは　かたければ","滝の音は　たえて久しく　なりぬれど","あらざらむ　この世のほかの　思ひ出に","めぐりあひて　見しやそれとも　わかぬまに","ありま山　ゐなの笹原　風吹けば","やすらはで　寝なましものを　さ夜ふけて","大江山　いく野の道の　遠ければ","いにしへの　奈良の都の　八重ざくら","夜をこめて　鳥のそらねは　はかるとも","いまはただ　思ひ絶えなむと　ばかりを","朝ぼらけ　宇治の川霧　絶え絶えに","恨みわび　ほさぬ袖だに　あるものを","もろともに　あはれと思へ　山ざくら","春の夜の　ゆめばかりなる　手枕に","心にも　あらでうき世に　ながらへば","あらし吹く　三室の山の　もみぢ葉は","さびしさに　宿をたち出でて　ながむれば","夕されば　門田の稲葉　おとづれて","音にきく　たかしの浜の　あだ波は","高砂の　尾上の桜　咲きにけり","憂かりける　人を初瀬の　山おろし","契りおきし　させもが露を　いのちにて","わたの原　漕ぎ出でて見れば　久方の","瀬をはやみ　岩にせかるる　滝川の","淡路島　かよふ千鳥の　鳴く声に","秋風に　たなびく雲の　たえ間より","長からむ　心もしらず　黒髪の","ほととぎす　鳴きつる方を　ながむれば","思ひわび　さても命は　あるものを","世の中よ　道こそなけれ　思ひ入る","ながらへば　またこのごろや　しのばれむ","夜もすがら　物思ふころは　明けやらで","嘆けとて　月やは物を　思はする","村雨の　露もまだ干ぬ　まきの葉に","難波江の　芦のかりねの　ひとよゆゑ","玉のをよ　たえなばたえね　ながらへば","見せばやな　雄島のあまの　袖だにも","きりぎりす　鳴くや霜夜の　さむしろに","わが袖は　潮干にみえぬ　沖の石の","世の中は　つねにもがもな　なぎさ漕ぐ","み吉野の　山の秋風　さ夜ふけて","おほけなく　うき世の民に　おほふかな","花さそふ　嵐の庭の　雪ならで","来ぬ人を　まつほの浦の　夕なぎに","風そよぐ　ならの小川の　夕ぐれは","人もをし　人もうらめし　あぢきなく","ももしきや　古き軒端の　しのぶにも"];
const CARDS=POEMS.map((upper,i)=>({id:i+1,upper,label:String(i+1).padStart(2,'0')+' '+upper}));const $=id=>document.getElementById(id);const S={mode:'practice',mine:[],op:[],dead:[],mb:[],ob:[],current:null,started:0,send:false,first:'mine',logs:[]};
function rand(n){if(n<=0)return 0;const lim=Math.floor(0x100000000/n)*n,b=new Uint32Array(1);do{crypto.getRandomValues(b)}while(b[0]>=lim);return b[0]%n}function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=rand(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function board(cards){const out=Array(27).fill(null),slots=shuffle([...Array(27).keys()]).slice(0,25);shuffle(cards).forEach((c,i)=>out[slots[i]]=c);return out}
function deal(){const d=shuffle(CARDS);S.mine=d.slice(0,25);S.op=d.slice(25,50);S.dead=d.slice(50);S.mb=board(S.mine);S.ob=board(S.op);S.current=null;S.send=false;S.logs=[];S.first=S.mode==='local'?(rand(2)?'opponent':'mine'):'mine';$('first').textContent='先手：'+(S.first==='mine'?'あなた':'相手');render();toast('100枚からランダムに25枚ずつ配りました')}
function start(mode){S.mode=mode;$('mode').textContent=mode==='local'?'2人ローカル対戦':'1人練習';$('status').textContent=mode==='local'?'両陣タップ可':'自陣のみ操作';$('first').textContent='先手：—';$('home').classList.remove('active');$('game').classList.add('active');deal()}
function esc(v){return v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}function cardEl(c,side,i){const b=document.createElement('button');b.className='card'+(!c?' empty':'');if(!c){b.disabled=true;return b}b.dataset.id=c.id;b.innerHTML='<small>'+c.id+'</small><span>'+esc(c.upper)+'</span>';if(S.current?.id===c.id)b.classList.add('target');b.addEventListener('click',()=>S.send&&side==='mine'?sendPick(c,i):take(c,side,i));return b}
function renderBoard(id,arr,side){const el=$(id);el.innerHTML='';arr.forEach((c,i)=>el.appendChild(cardEl(c,side,i)))}function render(){ $('myCount').textContent=S.mine.length;$('opCount').textContent=S.op.length;renderBoard('myBoard',S.mb,'mine');renderBoard('opBoard',S.ob,'opponent');$('send').disabled=!S.send||!S.mine.length;$('logCount').textContent=S.logs.length+'件';$('logs').innerHTML=S.logs.slice().reverse().map(x=>'<div class="log"><span>'+x.time+'</span><b>'+esc(x.kind)+'</b><span>'+esc(x.text)+'</span><strong>'+esc(x.result)+'</strong></div>').join('')}
function log(kind,text,result){S.logs.push({time:new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),kind,text,result});render()}function feedback(t){$('feedback').textContent=t}
function say(text){if(!('speechSynthesis'in window)){feedback('このブラウザでは音声読み上げが使えません');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ja-JP';u.rate=.86;speechSynthesis.speak(u)}
function read(){const pool=S.mode==='practice'?S.mine:[...S.mine,...S.op];if(!pool.length)return;const c=pool[rand(pool.length)];S.current=c;S.started=performance.now();$('reading').textContent='「'+c.upper+'……」';$('hint').textContent=S.mode==='practice'?'自陣の正しい札をタップしてください。':'両陣から正しい札を先にタップしてください。';feedback('読札：'+c.label);say(c.upper);render()}
function take(c,side,i){if(!S.current){feedback('先に「読み上げる」を押してください');return}const ms=Math.round(performance.now()-S.started);if(c.id!==S.current.id){log('お手つき',c.label,'ミス');feedback('お手つき：'+c.label);return}if(S.mode==='practice'&&side==='opponent'){feedback('練習モードでは自陣札のみを取ります');return}if(side==='mine'){S.mine=S.mine.filter(x=>x.id!==c.id);S.mb[i]=null}else{S.op=S.op.filter(x=>x.id!==c.id);S.ob[i]=null;S.send=!!S.mine.length}S.current=null;log('取得',c.label,ms+'ms');feedback(side==='mine'?'取得しました':'相手陣から取得。送札できます');if(!S.mine.length||!S.op.length){$('status').textContent=S.mine.length?'相手の勝ち':'あなたの勝ち';feedback('試合終了：'+$('status').textContent)}render()}
function sendPick(c,i){if(!S.send)return;S.mine=S.mine.filter(x=>x.id!==c.id);S.mb[i]=null;S.op.push(c);S.ob=board(S.op);S.send=false;log('送札',c.label,'相手へ');feedback(c.label+' を相手陣へ送りました');render()}
function showDeal(){$('mN').textContent=S.mine.length;$('oN').textContent=S.op.length;$('dN').textContent=S.dead.length;const mk=a=>a.map(c=>'<span class="chip">'+esc(c.label)+'</span>').join('');$('mineList').innerHTML=mk(S.mine);$('opList').innerHTML=mk(S.op);$('modal').classList.remove('hidden')}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1500)}
$('practice').onclick=()=>start('practice');$('local').onclick=()=>start('local');$('dealHome').onclick=()=>{start('practice');showDeal()};$('newGame').onclick=()=>{speechSynthesis?.cancel();$('game').classList.remove('active');$('home').classList.add('active')};$('read').onclick=read;$('stop').onclick=()=>speechSynthesis?.cancel();$('redeal').onclick=deal;$('relayout').onclick=()=>{S.mb=board(S.mine);S.ob=board(S.op);render();toast('配置をランダム化しました')};$('send').onclick=()=>S.send?feedback('自陣の札をタップして送札してください'):feedback('相手陣から取得した直後に送札できます');$('showDeal').onclick=showDeal;$('close').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')};